- type: rank
  id: RMCRankMajorGeneral
  name: Генерал-Майор
  prefix: Ген.М-р. #ГенМай.
  paygrade: O8

- type: rank
  id: RMCRankBrigadierGeneral
  name: Бригадний Генерал
  prefix: Бр.Г-л. #БрГен.
  paygrade: O7

- type: rank
  id: RMCRankColonel
  name: Полковник
  prefix: П-к. # Полк.
  paygrade: O6

- type: rank
  id: RMCRankLieutenantColonel
  name: Підполковник
  prefix: П.П-к. #Підполк.
  paygrade: O5

- type: rank
  id: RMCRankMajor
  name: Майор
  prefix: М-р. #Май.
  paygrade: O4

- type: rank
  id: RMCRankCaptain
  name: Капітан
  prefix: К-н. #Кап.
  paygrade: O3

- type: rank
  id: RMCRankFirstLT
  name: Перший Лейтенант
  prefix: 1 Л-т. 
  paygrade: O2

- type: rank
  id: RMCRankSecondLT
  name: Другий Лейтенант
  prefix: 2 Л-т.
  paygrade: O1
